/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *rcc_ahb1enr = (uint32_t *) 0x40023830; // rcc enable for AHB1 bus
	uint32_t *gpio_a_register = (uint32_t *) 0x40020000; // address for GPIO A register
	uint32_t *gpio_d_register = (uint32_t *) 0x40020C00; // address for GPIO D register

	*rcc_ahb1enr |= 0x1; // enable clock for GPIO port A
	*rcc_ahb1enr |= (0x1 << 3); // enable clock for GPIO port D

	*gpio_a_register &= ~(0x3); // reset mode for PA0

	*gpio_d_register &= ~(0x3 << 24); // reset mode for PD12;
	*gpio_d_register |= (0x1 << 24); // set PD12 as g/p output

	uint32_t *gpio_a_input = (uint32_t *) 0x40020010; // GPIO port A input address (GPIO_A_REGISTER + 0x10 offset)
	uint32_t *gpio_d_output = (uint32_t *) 0x40020C14; // GPIO port D input address (GPIO_D_REGISTER + 0x14 offset)

	while (1) {
		if (*gpio_a_input & 1) { // if first bit of gpio_a_input is 1
			*gpio_d_output &= ~(0x1 << 12); // set bit 12 to 0
		} else {
			*gpio_d_output |= 0x1 << 12; // set bit 12 to 1
		}
	}

}
